version: "3.9"
services:
  backend:
    build: .
    container_name: notescanner-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./user_notes:/app/user_notes
      - ./backend/chroma_storage:/app/backend/chroma_storage
    command: ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: notescanner-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/my-app/src:/app/src
      - ./frontend/my-app/public:/app/public
      - ./frontend/my-app/index.html:/app/index.html
      - ./frontend/my-app/vite.config.js:/app/vite.config.js
    command: ["npm", "run", "dev", "--", "--host"]